# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday002',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday002',
                'lib_path': 'tidytuesday002'},
  'syms': {'tidytuesday002.core': {'tidytuesday002.core.foo': ('core.html#foo', 'tidytuesday002/core.py')}}}
